name = "autopi-ha-docs"
compatibility_date = "2024-01-15"
routes = [
  { pattern = "autopi.homeassistant.m7kni.com", custom_domain = true }
]

[assets]
directory = "./site"
not_found_handling = "404-page"

[observability.logs]
enabled = true

